# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Anqi Zhu
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://anqizhu23.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/tree.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zhuant555@gmail.com
      link: mailto:zhuant555@gmail.com
 #   - name: WeChat
     # value: YourWeChatUsername
     # link: "#"
  follow:
    - name: Twitter
      link: https://twitter.com/amoshoo1
      username: "@YourTwitterUsername"
    - name: Facebook
      link: https://www.facebook.com/profile.php?id=100084497827706
  #  - name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: https://github.com/AnqiZhu23/
  #  - name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- name: RSS
     # link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
